# Generated by Django 4.0.4 on 2023-04-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='descripton',
            new_name='description',
        ),
    ]
